export const GO_COINS_NAV = 'GO_COINS_NAV';
export const GO_NEWS_NAV = 'GO_NEWS_NAV';
export const GO_TOOLS_NAV = 'GO_TOOLS_NAV';
export const GO_PORTFOLIO_NAV = 'GO_PORTFOLIO_NAV';

export const GO_MY_FAVORITES = 'GO_MY_FAVORITES';
export const GO_MY_FAVORITES_NEWS = 'GO_MY_FAVORITES_NEWS';
export const CLOSE_MY_FAVORITES = 'CLOSE_MY_FAVORITES';
export const CLOSE_MY_FAVORITES_NEWS = 'CLOSE_MY_FAVORITES_NEWS';

export const GO_HAMBURGER = 'GO_HAMBURGER';
export const CLOSE_HAMBURGER = 'CLOSE_HAMBURGER';

export const GO_TOP_COINS_SCREEN = 'GO_TOP_COINS_SCREEN';
export const GO_ALL_COINS_SCREEN = 'GO_ALL_COINS_SCREEN';
export const GO_EXCHANGES_SCREEN = 'GO_EXCHANGES_SCREEN';
export const GO_PAIRS_SCREEN = 'GO_PAIRS_SCREEN';

export const GO_CHART = 'GO_CHART';
export const BACK_TOP = 'BACK_TOP';
export const BACK_ALL = 'BACK_ALL';

export const GO_EXCHANGES_DETAILS = 'GO_EXCHANGES_DETAILS';
export const BACK_EXCHANGES = 'BACK_EXCHANGES';

export const GO_CHART_INFO = 'GO_CHART_INFO';
export const GO_MARKETS_INFO = 'GO_MARKETS_INFO';
export const BACK_CHART = 'BACK_CHART';

export const GO_DAILY = 'GO_DAILY';
export const GO_ALL_CHART = 'GO_ALL_CHART';

export const GO_LATEST_NAV = 'GO_LATEST_NAV';
export const GO_BITCOIN_NAV = 'GO_BITCOIN_NAV';
export const GO_ALTCOIN_NAV = 'GO_ALTCOIN_NAV';
export const GO_ICO_NAV = 'GO_ICO_NAV';
export const GO_ANALYSYS = 'GO_ANALYSYS';
export const GO_SPONSORED_NAV = 'GO_SPONSORED_NAV';
export const GO_DERIVATIVES_NAV = 'GO_DERIVATIVES_NAV';

export const GO_DETAIL_NEWS = 'GO_DETAIL_NEWS';
export const BACK_NEWS = 'BACK_NEWS';
export const FETCH_DATA = 'FETCH_DATA';

export const LIKED_POST = 'LIKED_POST';
export const LIKED_POST_LENGTH = 'LIKED_POST_LENGTH';
export const DISLIKES_POST = 'DISLIKES_POST';

export const LIKED_DETAIL_NEWS = 'LIKED_DETAIL_NEWS';
