export const FETCHING_COIN_DATA = 'FETCHING_COIN_DATA';
export const FETCHING_COIN_DATA_SUCCESS = 'FETCHING_COIN_DATA_SUCCESS';
export const FETCHING_COIN_DATA_FAIL = 'FETCHING_COIN_DATA_FAIL';

export const GO_COINS_NAV = 'GO_COINS_NAV';
export const GO_NEWS_NAV = 'GO_NEWS_NAV';
export const GO_TOOLS_NAV = 'GO_TOOLS_NAV';
export const GO_PORTFOLIO_NAV = 'GO_PORTFOLIO_NAV';

export const GO_TOP_COINS_SCREEN = 'GO_TOP_COINS_SCREEN';
export const GO_ALL_COINS_SCREEN = 'GO_ALL_COINS_SCREEN';

export const GO_CHART = 'GO_CHART';
export const BACK_TOP = 'BACK_TOP';

export const GO_CHART_INFO = 'GO_CHART_INFO';
export const GO_MARKETS_INFO = 'GO_MARKETS_INFO';

export const FETCHING_MARKET_DATA = 'FETCHING_MARKET_DATA';
export const FETCHING_MARKET_DATA_SUCCESS = 'FETCHING_MARKET_DATA_SUCCESS';
export const FETCHING_MARKET_DATA_FAIL = 'FETCHING_MARKET_DATA_FAIL';

export const GO_DAILY = 'GO_DAILY';
export const GO_ALL_CHART = 'GO_ALL_CHART';

export const GO_BITCOIN_NAV = 'GO_BITCOIN_NAV';
export const GO_ALTCOIN_NAV = 'GO_ALTCOIN_NAV';
export const GO_ICO_NAV = 'GO_ICO_NAV';
export const GO_ANALYSYS = 'GO_ANALYSYS';
export const GO_SPONSORED_NAV = 'GO_SPONSORED_NAV';
export const GO_DERIVATIVES_NAV = 'GO_DERIVATIVES_NAV';

export const GO_DETAIL_NEWS = 'GO_DETAIL_NEWS';
export const BACK_NEWS = 'BACK_NEWS';

export const LIKED_POST = 'LIKED_POST';
export const DISLIKES_POST = 'DISLIKES_POST';
